name: CI

on:
  pull_request:
    branches: [main]
    # types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: ./.github/actions/setup
      #   with:
      #     deploy_key: "${{ secrets.DEPLOY_KEY_LLAMA_CODESHIELD }}"
      # - name: Test core
      #   run: |
      #     pytest -x tests
